# Generated by Django 5.1.1 on 2025-02-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lelang', '0002_baranglelang_penjual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baranglelang',
            name='lelang_dibuka',
            field=models.DateTimeField(),
        ),
    ]
