# Generated by Django 5.1.1 on 2025-02-18 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lelang', '0003_alter_baranglelang_lelang_dibuka'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='baranglelang',
            name='penjual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang_lelang', to=settings.AUTH_USER_MODEL),
        ),
    ]
